name = "LightPropagation"
uuid = "bd080553-88c9-414f-9879-667caf467699"
authors = ["Michael Helton <heltonmc@umich.edu>"]
version = "0.8.0"

[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
FastGaussQuadrature = "442a2c76-b920-505d-bb47-c5924d526838"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
JLD = "4138dd39-2aa7-5051-a626-17a0bb65d9c8"
LsqFit = "2fda8390-95c7-5789-9bda-21331edee243"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
PkgBenchmark = "32113eaa-f34f-5b0d-bd6c-c81e245fc73d"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"

[compat]
FastGaussQuadrature = "v0.4"
ForwardDiff = "v0.10"
JLD = "v0.12"
LsqFit = "v0.12"
Parameters = " v0.12"
SpecialFunctions = "v0.7, v1.0"
julia = "1.5"
